// Real response captured from the backend (USE_MOCK_LLM=true) on 2026-06-30.
// Shape matches the spec data contract exactly.
// ontologyRuleDescription / ontologyRulePattern are now joined from ontology_rules via FK.

export const MOCK_DOCUMENT = {
  id: "d2922c3c-e6ac-42f4-8a84-508a461cc09c",
  originalFilename: "test_doc.txt",
  rawText:
    "John Smith, born January 15 1985, lives at 123 Main Street, Chicago IL 60601. His SSN is 123-45-6789 and email is john.smith@example.com. His phone number is (312) 555-0192. He worked at Acme Corp from 2010 to 2020.\n",
  status: "in_review",
  uploadedAt: "2026-06-30T07:57:49.158106+00:00",
  llmDetector: "Mock LLM",
  spans: [
    {
      id: "fab028c1-ad6d-46f1-aa23-09bd3358f492",
      text: "123-45-6789",
      startOffset: 89,
      endOffset: 100,
      type: "SSN",
      llmConfidence: 0.98,
      llmRationale: "This is a US Social Security Number in the standard NNN-NN-NNNN format. It is a highly sensitive personal identifier.",
      ontologyRuleId: "6384c366-b6c0-441d-befd-b923899e6a2a",
      ontologyRuleDescription: "Formatted SSN (NNN-NN-NNNN) or unformatted 9-digit number preceded by SSN context words within 20 characters.",
      ontologyRulePattern: String.raw`\b(?:\d{3}-\d{2}-\d{4}|(?:ssn|social security|tax id)[^\d]{0,20}\d{9})\b`,
      source: "BOTH",
      conflict: false,
      riskTier: "high",
      priorityScore: 9.04,
      status: "pending",
    },
    {
      id: "072307d1-6a20-4395-b489-bfad6fdd14d0",
      text: "John Smith",
      startOffset: 0,
      endOffset: 10,
      type: "NAME",
      llmConfidence: 0.91,
      llmRationale: "Full personal name appearing at the start of the document as the subject. High confidence this is a real individual's name.",
      ontologyRuleId: null,
      ontologyRuleDescription: null,
      ontologyRulePattern: null,
      source: "LLM",
      conflict: false,
      riskTier: "medium",
      priorityScore: 6.18,
      status: "pending",
    },
    {
      id: "d14e8917-40f4-4a20-8973-0715a63054f1",
      text: "john.smith@example.com",
      startOffset: 114,
      endOffset: 136,
      type: "EMAIL",
      llmConfidence: 0.96,
      llmRationale: "Valid email address in personal name format. Both the LLM and ontology pattern matched this span.",
      ontologyRuleId: "b4850ba0-f382-4abd-a5d2-dabeac127e39",
      ontologyRuleDescription: "Standard email address pattern.",
      ontologyRulePattern: String.raw`\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b`,
      source: "BOTH",
      conflict: false,
      riskTier: "medium",
      priorityScore: 6.08,
      status: "pending",
    },
    {
      id: "e29bba04-00ca-4616-974c-f0014dba981c",
      text: "123 Main Street",
      startOffset: 43,
      endOffset: 58,
      type: "ADDRESS",
      llmConfidence: null,
      llmRationale: null,
      ontologyRuleId: "b25e736c-1cad-4de6-81bc-3c314e73de67",
      ontologyRuleDescription: "Street address: house number followed by street-like words ending in a recognized suffix (Street, Ave, Road, etc.).",
      ontologyRulePattern: String.raw`\b\d{1,6}\s+[A-Z][A-Za-z0-9.'-]*(?:\s+[A-Z][A-Za-z0-9.'-]*){0,5}\s+(?:St|Street|Ave|Avenue|Rd|Road|Blvd|Boulevard|Dr|Drive|Ln|Lane|Way|Court|Ct|Circle|Cir|Pl|Place)\b\.?`,
      source: "ONTOLOGY",
      conflict: false,
      riskTier: "medium",
      priorityScore: 6.0,
      status: "pending",
    },
    {
      id: "bb463feb-d006-4582-a0a7-5c6e8d05202b",
      text: "Main Street",
      startOffset: 47,
      endOffset: 58,
      type: "NAME",
      llmConfidence: null,
      llmRationale: null,
      ontologyRuleId: "c22e5847-370b-4d93-b819-418151e27496",
      ontologyRuleDescription: "Capitalized multi-word sequences, excluding common stopwords and sentence-leading false positives. Uses structural heuristics rather than a fixed regex.",
      ontologyRulePattern: null,
      source: "ONTOLOGY",
      conflict: true,
      riskTier: "medium",
      priorityScore: 7.2,
      status: "pending",
    },
    {
      id: "0a7d8bd4-b178-4631-b754-029023661971",
      text: "(312) 555-0192",
      startOffset: 158,
      endOffset: 172,
      type: "PHONE",
      llmConfidence: null,
      llmRationale: null,
      ontologyRuleId: "c0667da3-c3dc-4c9f-8af0-825d96e582ed",
      ontologyRuleDescription: "Common US and international phone number formats (digits with optional hyphens, dots, or spaces).",
      ontologyRulePattern: String.raw`(?<!\d)(?:\+?\d{1,3}[-.\s]?)?(?:\(?\d{3}\)?[-.\s]?)\d{3}[-.\s]?\d{4}(?!\d)`,
      source: "ONTOLOGY",
      conflict: false,
      riskTier: "medium",
      priorityScore: 6.0,
      status: "pending",
    },
    {
      id: "a9b66afe-06eb-4da0-912d-0e5124ff00ed",
      text: "Acme Corp",
      startOffset: 187,
      endOffset: 196,
      type: "NAME",
      llmConfidence: 0.52,
      llmRationale: "Possible organization name. Lower confidence — could be a company rather than a personal identifier.",
      ontologyRuleId: "c22e5847-370b-4d93-b819-418151e27496",
      ontologyRuleDescription: "Capitalized multi-word sequences, excluding common stopwords and sentence-leading false positives. Uses structural heuristics rather than a fixed regex.",
      ontologyRulePattern: null,
      source: "BOTH",
      conflict: false,
      riskTier: "low",
      priorityScore: 3.1,
      status: "pending",
    },
  ],
};

export const MOCK_SUMMARY = {
  totalSpans: 7,
  byType: { SSN: 1, NAME: 3, EMAIL: 1, ADDRESS: 1, PHONE: 1 },
  byRiskTier: { high: 1, medium: 6, low: 1 },
  conflicts: 1,
};

export const MOCK_AUDIT = [];

export const MOCK_BATCH = {
  uploadResponse: {
    batchId: "b1000000-0000-0000-0000-000000000001",
    totalDocuments: 4,
    succeeded: 3,
    failed: [{ filename: "corrupted.pdf", reason: "extraction_failed" }],
  },
  batch: {
    batchId: "b1000000-0000-0000-0000-000000000001",
    status: "partial_failure",
    totalDocuments: 4,
    documents: [
      {
        id: "d2922c3c-e6ac-42f4-8a84-508a461cc09c",
        originalFilename: "case_014.pdf",
        status: "in_review",
        totalSpans: 7,
        pendingCount: 6,
        unresolvedHighRiskCount: 1,
        conflictCount: 1,
        docPriorityScore: 46.5,
      },
      {
        id: "d2922c3c-e6ac-42f4-8a84-508a461cc09d",
        originalFilename: "case_022.docx",
        status: "in_review",
        totalSpans: 4,
        pendingCount: 4,
        unresolvedHighRiskCount: 0,
        conflictCount: 1,
        docPriorityScore: 18.2,
      },
      {
        id: "d2922c3c-e6ac-42f4-8a84-508a461cc09e",
        originalFilename: "case_007.txt",
        status: "in_review",
        totalSpans: 2,
        pendingCount: 0,
        unresolvedHighRiskCount: 0,
        conflictCount: 0,
        docPriorityScore: 0,
      },
    ],
  },
};
